AdsetIntegrador.MVC/Models/ErrorViewModel.cs
namespace AdsetIntegrador.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdsetIntegrador.MVC/ViewModels/ItemDeSerieViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AdsetIntegrador.MVC.ViewModels
{
    public class ItemDeSerieViewModel
    {
        [Key]
        public int ItemDeSerieId { get; set; }
        public string Nome { get; set; }
    }
}

AdsetIntegrador.MVC/ViewModels/VeiculoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdsetIntegrador.MVC.ViewModels
{
    public class VeiculoViewModel
    {
        [Key]
        public int VeiculoId { get; set; }
        [Required(ErrorMessage = "Preencha a Marca")]
        [MaxLength(50)]
        public string Marca { get; set; }
        [Required(ErrorMessage = "Preencha o Modelo")]
        [MaxLength (100)]
        public string Modelo { get; set; }
        [Required(ErrorMessage = "Preencha o Ano")]
        public int Ano { get; set; }
        [Required(ErrorMessage = "Preencha a Placa")]
        [MaxLength (10)]
        public string Placa { get; set; }
        [Range(typeof(decimal), "0", "9999999999")]
        public decimal? Km { get; set; }
        [Required(ErrorMessage = "Preencha a Cor")]
        [MaxLength (10)]
        public string Cor { get; set; }
        [Range(typeof(decimal),"0","9999999999")]
        [Required(ErrorMessage = "Preencha o Preço")]
        public decimal Preco { get; set; }
        [MaxLength (255)]
        public string? Foto { get; set; }
        public List<string>? Fotos { get; set; }
        [ScaffoldColumn(false)]
        public DateTime DataDeCadastro { get; set; }
        public virtual IEnumerable<ItemDeSerieViewModel>? ItensDeSerie { get; set; }
    }
}

AdsetIntegrador.MVC/Controllers/HomeController.cs
using AdsetIntegrador.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AdsetIntegrador.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdsetIntegrador.MVC/Controllers/VeiculoController.cs
using AdsetIntegrador.MVC.ViewModels;
using AdsetIntegrator.Application.Interface;
using Microsoft.AspNetCore.Mvc;
using AdsetIntegrator.Domain.Entities;
using AutoMapper;

namespace AdsetIntegrador.MVC.Controllers
{
    public class VeiculoController : Controller
    {
        private readonly IVeiculoAppService _veiculoAppService;

        public VeiculoController(IVeiculoAppService veiculoAppService)
        {
            _veiculoAppService = veiculoAppService;
        }

        public ActionResult Index()
        {
            var clienteViewModel = Mapper.Map<IEnumerable<Veiculo>, IEnumerable<VeiculoViewModel>>(_veiculoAppService.GetAll());
            return View(clienteViewModel);
        }

        public ActionResult Details(int id)
        {
            var veiculo = _veiculoAppService.GetbyId(id);
            var veiculoViewModel = Mapper.Map<Veiculo, VeiculoViewModel>(veiculo);

            return View(veiculoViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VeiculoViewModel veiculo)
        {
            if (ModelState.IsValid)
            {
                var veiculoDomain = Mapper.Map<VeiculoViewModel, Veiculo>(veiculo);
                _veiculoAppService.Add(veiculoDomain);

                return RedirectToAction("Index");
            }
            return View(veiculo);
        }

        public ActionResult Edit(int id)
        {
            var veiculo = _veiculoAppService.GetbyId(id);
            var veiculoViewModel = Mapper.Map<Veiculo, VeiculoViewModel>(veiculo);

            return View(veiculoViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VeiculoViewModel veiculo, List<IFormFile> formFileMultiple)
        {
            if (ModelState.IsValid)
            {
                List<string> files = new List<string>();
                
                if (formFileMultiple.Count > 0)
                {
                    foreach (var foto in formFileMultiple)
                    {
                        string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/FotosVeiculos");

                        //create folder if not exist
                        if (!Directory.Exists(path))
                            Directory.CreateDirectory(path);
                        string fileNameWithPath = Path.Combine(path, foto.FileName);

                        using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                        {
                            foto.CopyTo(stream);
                        }

                        files.Add(foto.FileName);
                    }
                }
                veiculo.Fotos = files;

                var veiculoDomain = Mapper.Map<VeiculoViewModel, Veiculo>(veiculo);
                _veiculoAppService.Update(veiculoDomain);

                return RedirectToAction("Index");
            }
            return View(veiculo);
         
        
    }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            var veiculo = _veiculoAppService.GetbyId(id);
            _veiculoAppService.Delete(veiculo);

            return Json(new { success = true });
        }
    }
}

AdsetIntegrador.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AdsetIntegrador.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdsetIntegrador</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdsetIntegrador.MVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header class="d-flex flex-wrap justify-content-center py-3 px-4  border-bottom ">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <img src="~/images/Logo.svg" alt="" srcset="">
        </a>
        <div id="btnSwitch" class="form-check form-switch d-flex  " data-checked="false">
            <div class="btn-group align-items-center btn-group-lg  " role="group" aria-label="Basic example">
                <label class="form-check-label btn order-0" for="flexSwitchCheckDefault">
                    <i class="bi bi-brightness-high"></i>
                </label>
                <input class="form-check-input btn order-1 m-0 rounded-5 border-2 border-primary  " type="checkbox"
                        role="switch" id="flexSwitchCheckDefault">
                <label class="form-check-label btn order-2 " for="flexSwitchCheckDefault">
                    <i class="bi bi-moon-fill"></i>
                </label>
            </div>
        </div>
    </header>
   

    <main role="main" class="pb-3">
        @RenderBody()
    </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AdsetIntegrador - <a asp-area="" asp-controller="Veiculo" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/jquery.alerts.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/veiculo.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AdsetIntegrador.MVC/Views/Veiculo/Create.cshtml
@using AdsetIntegrator.Domain.Entities;
@model AdsetIntegrador.MVC.ViewModels.VeiculoViewModel

@{
    ViewBag.Title = "Create";
}


<div class="container">
    <div class="row">
        
        @using (Html.BeginForm()) 
        {
            @Html.AntiForgeryToken()

            <div class="mb-3 row align-items-end ">
                <h4 class="my-3">Novo veículo</h4>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col col-12 col-sm-6  col-lg-4 col-xxl">
                    @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                        @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
                </div>
                <div class="col col-12 col-sm-6  col-lg-4 col-xxl">
                    @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                            @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                        @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
                </div>
                <div class="col col-12 col-sm-6  col-lg-4 col-xxl">
                    @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50"} })
                        @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
                </div>
                <div class="col col-12 col-sm-6  col-lg-4 col-xl-3  col-xxl">
                    @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                        @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-6 col-sm-4  col-lg-4 col-xl-3 col-xxl">
                    @Html.LabelFor(model => model.Cor, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                    @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
                </div>
                <div class="col col-12 col-sm-6  col-lg-4 col-xl-3 col-xxl">
                    @Html.LabelFor(model => model.Km, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Km, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                        @Html.ValidationMessageFor(model => model.Km, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-6 col-lg-4 col-xl-3 col-xxl">
                    @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
                        @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary  bg-opacity-50" } })
                        @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row border-bottom pb-3 mb-3">
                <div class="col col-6">
                    <label for="opcionais" class="form-label">Opcionais</label>
                    <input id="opcionais-search" data-live-search="true" onkeyup="filterList()"
                            class="form-control  mb-3 form-control-sm rounded-5 bg-body-secondary  bg-opacity-50  "
                            aria-label=".form-select-lg example"/>
                    <ul id="list-opcionais" class="list-group overflow-auto ">
                        <li class="list-group-item">
                            <input class="form-check-input me-1" type="checkbox" name="item[]" value="" id="firstCheckbox">
                            <label class="form-check-label" for="firstCheckbox">Cambio automatico</label>
                        </li>
                        <li class="list-group-item">
                            <input class="form-check-input me-1" type="checkbox" name="item[]" value="" id="secondCheckbox">
                            <label class="form-check-label" for="secondCheckbox">Trava Eletrica</label>
                        </li>
                        <li class="list-group-item">
                            <input class="form-check-input me-1" type="checkbox" name="item[]" value="" id="thirdCheckbox">
                            <label class="form-check-label" for="thirdCheckbox">Ar condicionado</label>
                        </li>
                            
                    </ul>
                </div>
               
                <div class="col col-6">
                    @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2",@for="formFileMultiple" })
                        <input class="form-control rounded-start-4 " type="file" id="formFileMultiple" multiple />
                </div>
            </div>
            <div class="col p-xl-0 d-flex justify-content-end flex-xxl-grow-0 gap-3  ">
                <a href="veiculo/index" type="hidde" class="btn btn-danger  mb-3 "><i class="bi bi-x"></i> Cancelar</a>
                <button type="hidde" class="btn btn-success  mb-3 "><i class="bi bi-check-lg"></i> Salvar</button>
            </div>
        }
        </div>
    </div>

AdsetIntegrador.MVC/Views/Veiculo/Delete.cshtml
@model AdsetIntegrador.MVC.ViewModels.VeiculoViewModel

@{
    ViewBag.Title = "Delete";
}


<h3>Você tem certeza que deseja deletar o veículo - @Html.DisplayFor(model => model.Marca) @Html.DisplayFor(model => model.Modelo)</h3>
<div>
   
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AdsetIntegrador.MVC/Views/Veiculo/Details.cshtml
@model AdsetIntegrador.MVC.ViewModels.VeiculoViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>VeiculoViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ano)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ano)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Km)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Km)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VeiculoId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AdsetIntegrador.MVC/Views/Veiculo/Edit.cshtml
@model AdsetIntegrador.MVC.ViewModels.VeiculoViewModel

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="row">
        <form asp-action="Edit" method="post" enctype="multipart/form-data">
        
            @Html.AntiForgeryToken()
 
            <div class="mb-3 row align-items-end ">
                <h4 class="my-3">Editar veículo</h4>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.VeiculoId)
                <div class="col col-12 col-sm-6  col-lg-4 col-xxl">
                    @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                    @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
                </div>
                <div class="col col-12 col-sm-6  col-lg-4 col-xxl">
                    @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                    @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
                </div>
                <div class="col col-12 col-sm-6  col-lg-4 col-xxl">
                    @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50"} })
                    @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
                </div>
                <div class="col col-12 col-sm-6  col-lg-4 col-xl-3  col-xxl">
                    @Html.LabelFor(model => model.Ano, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                    @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-6 col-sm-4  col-lg-4 col-xl-3 col-xxl">
                    @Html.LabelFor(model => model.Cor, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                    @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
                </div>
                <div class="col col-12 col-sm-6  col-lg-4 col-xl-3 col-xxl">
                    @Html.LabelFor(model => model.Km, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Km, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary bg-opacity-50" } })
                    @Html.ValidationMessageFor(model => model.Km, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-6 col-lg-4 col-xl-3 col-xxl">
                    @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
                    @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control mb-3 form-control-sm rounded-5 bg-body-secondary  bg-opacity-50" } })
                    @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row border-bottom pb-3 mb-3">
                <div class="col col-6">
                    <label for="opcionais" class="form-label">Opcionais</label>
                    <input id="opcionais-search" data-live-search="true" onkeyup="filterList()"
                            class="form-control  mb-3 form-control-sm rounded-5 bg-body-secondary  bg-opacity-50  "
                            aria-label=".form-select-lg example" />
                    <ul id="list-opcionais" class="list-group overflow-auto ">
                        <li class="list-group-item">
                            <input class="form-check-input me-1" type="checkbox" name="item[]" value="" id="firstCheckbox">
                            <label class="form-check-label" for="firstCheckbox">Cambio automatico</label>
                        </li>
                        <li class="list-group-item">
                            <input class="form-check-input me-1" type="checkbox" name="item[]" value="" id="secondCheckbox">
                            <label class="form-check-label" for="secondCheckbox">Trava Eletrica</label>
                        </li>
                        <li class="list-group-item">
                            <input class="form-check-input me-1" type="checkbox" name="item[]" value="" id="thirdCheckbox">
                            <label class="form-check-label" for="thirdCheckbox">Ar condicionado</label>
                        </li>

                    </ul>
                </div>

                <div class="col col-6">
                    @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2",@for="formFileMultiple" })
                    <input class="form-control rounded-start-4 " name="formFileMultiple" type="file" id="formFileMultiple" multiple />
                </div>
            </div>

            <div class="col p-xl-0 d-flex justify-content-end flex-xxl-grow-0 gap-3  ">
                <a href="veiculo/index" type="hidde" class="btn btn-danger  mb-3 "><i class="bi bi-x"></i> Cancelar</a>
                <button type="hidde" class="btn btn-success  mb-3 "><i class="bi bi-check-lg"></i> Salvar</button>
            </div>
        </form>
    </div>
</div>